openapi: 3.1.0
info:
  title: Chat API
  version: "1.0.0"
paths:
  /chat:
    post:
      summary: Chat Endpoint
      description: Accepts user input and returns a dynamic response.
      requestBody:
        description: User input for the chat endpoint.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_input:
                  type: string
                  example: "Hello, Chat API!"
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "You said: Hello, Chat API!"
servers:
  - url: http://127.0.0.1:8000
    description: Local Chat API Server
